'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class File
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BrailleApps.File", GetType(File).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property _63_big() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_63_big", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property A() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("A", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ADB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ADB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property angka_0() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("angka_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property angka_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("angka_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property angka_10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("angka_10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property angka_2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("angka_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property angka_3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("angka_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property angka_4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("angka_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property angka_5() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("angka_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property angka_6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("angka_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property angka_7() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("angka_7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property angka_8() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("angka_8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property angka_9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("angka_9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property B() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("B", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property braille_apps_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("braille_apps_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property C() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("C", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property D() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property E() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("E", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property F() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("F", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Foto__433__Agung_Firmansyah() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Foto__433__Agung_Firmansyah", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Foto__436__Alfin_Ananda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Foto__436__Alfin_Ananda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Foto__449__Iqbal_Nurfaozi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Foto__449__Iqbal_Nurfaozi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Foto__455__M__Rifani() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Foto__455__M__Rifani", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property G() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("G", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Graviti_Braille_Apps() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Graviti_Braille_Apps", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property H() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("H", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property Hey() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Hey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property I() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("I", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend Shared ReadOnly Property icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property ini() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ini", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property J() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("J", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property K() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("K", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Keren() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Keren", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property L() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("L", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property M() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("M", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property N() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("N", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property O() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("O", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property P() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("P", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Profile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Profile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property Q() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Q", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property R() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("R", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property S() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("S", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property smk_bisa_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smk_bisa_copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property T() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("T", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Technology_HD_Backgrounds() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Technology_HD_Backgrounds", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property tkjadb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tkjadb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property tkjadbbackground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tkjadbbackground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property U() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("U", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property V() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("V", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property vb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property W() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("W", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property Windows_Navigation_Start() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Windows_Navigation_Start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property X() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("X", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property Y() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Y", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend Shared ReadOnly Property Z() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Z", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
